pad-ws/pad.ws

src/frontend/index.html, src/frontend/index.tsx, src/frontend/package.json, src/frontend/src/App.tsx, src/frontend/src/CustomEmbeddableRenderer.tsx, src/frontend/src/ExcalidrawWrapper.tsx, src/frontend/src/lib/ExcalidrawElementFactory.ts, src/frontend/src/pad/containers/Dashboard.tsx, src/frontend/src/pad/editors/HtmlEditor.tsx, src/frontend/src/ui/MainMenu.tsx, src/frontend/src/utils/elementPlacement.ts, src/frontend/yarn.lock
Inspired by [zsviczian](https://github.com/zsviczian) and its Excalidraw plugin for Obsidian, we're moving to a fork of Excalidraw maintained at [atyrode/excalidraw](https://github.com/atyrode/excalidraw) to bypass some limitations and shortcomings of the Excalidraw "custom app" system and its imperative API!
The goal is to keep the changes in the Excalidraw source code as minimal as possible, and rely as much as possible on this repository code and logic to keep improving pad.ws 😸
=> refactor: switch to @atyrode/excalidraw

src/frontend/package.json, src/frontend/yarn.lock
Replaces "*" in `package.json` to a specific version of [our fork of Excalidraw](https://github.com/atyrode/excalidraw/tree/pad.ws) to a specific version from now on as well.
=> chore: update Excalidraw dependency to version 0.18.0-1

.github/workflows/docker-build.yml
This adds `platforms: linux/amd64,linux/arm64`to the `docker-build.yml` GitHub action of the repository to cover more architectures.
=> chore: add support for multi-platform builds in Docker workflow

src/frontend/src/CustomEmbeddableRenderer.tsx, src/frontend/src/pad/editors/Editor.tsx, src/frontend/src/pad/editors/HtmlEditor.tsx, src/frontend/src/pad/editors/LanguageSelector.tsx, src/frontend/src/pad/editors/index.ts, src/frontend/src/styles/Editor.scss, src/frontend/src/styles/index.scss, src/frontend/src/ui/MainMenu.tsx
- Introduced a new Editor component for code editing with language support.
- Updated HtmlEditor to utilize the new Editor component for HTML content editing.
- Added LanguageSelector for selecting programming languages in the Editor.
- Enhanced state management in HtmlEditor to load content from customData.
- Implemented auto-save functionality in the Editor to persist changes.
- Updated styles for the new Editor component and its toolbar.
- Add code editor option to MainMenu.
=> feat: add custom Editor component

src/frontend/src/ExcalidrawWrapper.tsx
The grid settings were different in the initial data passed to Excalidraw meaning you could load the website and see a different grid behind the modal, than once you sign in.
=> fix: unified grid settings

.github/workflows/docker-build.yml, Dockerfile
The PR #23 complicated the CI/CD workflow too much and this reverts part of its logic to simplify the building flow.
=> fix: update CI workflow for consistency, change manifest/digest logic

.github/workflows/docker-build.yml
Seems like I wasn't done with trouble in #23 and #24. I tried to implement a better but more complex approach at multi-job multi-platform build but was not succesful and therefore will revert to a single-job, multi-platform build for the pad.ws packages.
=> refactor: simplify Docker build workflow

src/frontend/src/api/apiUtils.ts, src/frontend/src/api/hooks.ts, src/frontend/src/api/queryClient.ts
- Added a new function to handle unauthorized errors by updating the auth state in the query cache, triggering the AuthModal.
- Updated the existing response handling to incorporate the new unauthorized error handling.
- Improved clarity in the response handling logic for different status codes, including 204 and JSON responses.
- Updated the queryClient configuration to rename the cacheTime property to gcTime for clarity, indicating its purpose more accurately as garbage collection time.
=> fix: better handling of 401 errors to trigger auth modal

src/backend/db.py
for issue #28
pad start failed with `socket.gaierror: [Errno -2] Name or service not known`
=> fix db url parse when password contains '@'

src/frontend/index.scss, src/frontend/src/CustomEmbeddableRenderer.tsx, src/frontend/src/ExcalidrawWrapper.tsx
This makes the click-through property of embeddable now conditional to the user not scrolling.
This greatly enhance the usability on MacOS and trackpads that allow scrolling with fingers, as the scrolling would be abruptly interrupted as soon as the mouse hovered any embeddable, making the navigation experience quite frustrating.
=> fix: allow scrolling over embeddables

src/frontend/package.json, src/frontend/src/CustomEmbeddableRenderer.tsx, src/frontend/src/ExcalidrawWrapper.tsx, src/frontend/src/types/settings.ts, src/frontend/src/ui/MainMenu.tsx, src/frontend/src/ui/Range.scss, src/frontend/src/ui/Range.tsx, src/frontend/src/ui/SettingsDialog.scss, src/frontend/src/ui/SettingsDialog.tsx, src/frontend/src/utils/canvasUtils.ts, src/frontend/yarn.lock
This adds a new Settings menu in the main menu of [pad.ws](https://pad.ws):
Currently, it allows to change the "lock time" of embeds when scrolling the view to move around:
=> feat: add settings menu

src/backend/routers/canvas.py, src/frontend/src/App.tsx, src/frontend/src/ExcalidrawWrapper.tsx, src/frontend/src/pad/buttons/ActionButton.tsx, src/frontend/src/utils/posthog.ts
- Removed the canvas_saved event tracking from the save_canvas function in canvas.py to streamline the code.
- Updated the App component to eliminate the app_loaded event tracking.
- Integrated PostHog capture in ExcalidrawWrapper for user sign-in events.
- Refactored ActionButton to update event names for better clarity and removed redundant tracking calls.
- Simplified PostHog initialization by removing unnecessary session recording options.
=> refactor: remove most of the telemetry

src/frontend/src/App.tsx
I was too zealous in #41 and removed a workaround making Action Button possible (for now). This PR restores the functionnality.
=> fix: re-integrate excalidrawAPI into window object

src/backend/default_canvas.json, src/frontend/src/CustomEmbeddableRenderer.tsx, src/frontend/src/pad/buttons/ActionButton.tsx, src/frontend/src/pad/containers/Terminal.scss, src/frontend/src/pad/containers/Terminal.tsx, src/frontend/src/pad/index.ts, src/frontend/src/ui/MainMenu.tsx
This refactor the existing Terminal feature into its own component and exposes it as a module on [pad.ws](https://pad.ws) as !terminal:
This also makes them persistent.
=> feat: add persistent terminal module

src/frontend/src/AuthGate.tsx, src/frontend/src/env.d.ts, src/frontend/vite.config.mts
This addresses #49 and #17. The `AuthGate.tsx` file use to have an hardcoded value looping back to `https://coder.pad.ws`. It now reads from the CODER_URL environment variable that's provided at build time.
The `vite.config.mts` file was added to map the variable to work with Vite, for devs.
=> fix: update AuthGate to use environment variable for Coder URL

src/frontend/src/CustomEmbeddableRenderer.scss, src/frontend/src/CustomEmbeddableRenderer.tsx
This locks embeds while Hand tool is selected as well as indicates it next to the lock.
This should help mobile users to navigate and put the focus on "moving around" with Hand tool whereas "cursor" tool should focus on clicking/selecting.
=> feat: hand tool locks embeds

src/frontend/src/ui/MainMenu.tsx, src/frontend/src/ui/SettingsDialog.scss, src/frontend/src/ui/SettingsDialog.tsx
- Removes "toggle grid", "view mode" and "zen mode" from the Main menu, as they are available on right clicking the canvas.
- Add a "restore tutorial canvas" button in settings
=> refactor: simplify main menu

README.md
- Added detailed instructions for creating an audience in the Keycloak client settings, including configuration of client scopes and mappers.
- Enhanced clarity of the README to assist users in setting up audience management effectively.
=> docs: update README with audience creation steps

src/backend/database/service/pad_service.py, src/backend/routers/pad_router.py
- Updated create_pad method in PadService to include token_data for user creation failsafe, allowing automatic user creation if the owner does not exist.
- Modified error handling in pad retrieval to return an empty list instead of raising an error when the owner is not found, improving API robustness.
- Adjusted pad_router to pass token_data during pad creation, ensuring user synchronization with authentication data.
=> fix: add user creation failsafe mechanism

src/backend/database/service/pad_service.py, src/backend/routers/pad_router.py
- Modified create_pad method in PadService to accept user_session instead of token_data, enhancing user creation logic when the owner does not exist.
- Improved error handling during user creation to manage potential race conditions and provide clearer logging.
- Updated pad_router to pass user_session during pad creation, ensuring synchronization with user authentication data.
=> fix: user creation failsafe to rely on UserSession

.env.template, README.md
This addresses the core issue of #67, where using a custom workspace name but not providing the `.env` value that matches it would have the backend default to assuming the workspace is called `ubuntu` which could critically fail the app's startup.
- Introduced a new environment variable, CODER_WORKSPACE_NAME, in the .env.template to allow users to specify a custom workspace name.
- Updated the README to include instructions for setting the CODER_WORKSPACE_NAME, enhancing clarity for users configuring their environment.
=> fix: add CODER_WORKSPACE_NAME to .env.template and update README

scripts/startup.sh, src/backend/main.py, src/backend/routers/app_router.py, src/backend/routers/workspace_router.py, src/frontend/index.html, src/frontend/index.tsx, src/frontend/src/AuthGate.tsx, src/frontend/src/BuildVersionCheck.tsx, src/frontend/src/api/configService.ts, src/frontend/src/api/hooks.ts, src/frontend/src/global.d.ts, src/frontend/src/utils/canvasUtils.ts, src/frontend/src/utils/posthog.ts, src/frontend/vite.config.mts
This allows the app to send a refresh on the client if there is an update.
- Introduced a new router for application-related endpoints, including a `/build-info` endpoint to serve current build information from a generated JSON file.
- Implemented a Vite plugin to generate `build-info.json` during the build process, containing a unique build hash and timestamp.
- Added a `BuildVersionCheck` component in the frontend to monitor build version changes and refresh the application when a new version is detected.
- Updated existing routers to include necessary imports for the new functionality.
=> feat: add app router and build info endpoint

src/backend/database/database.py, src/backend/database/migrations/versions/2025_05_02_2055-migrate_canvas_data.py, src/backend/database/migrations/versions/2025_05_04_2310-create_schema.py
- Modified the `init_db` function to let Alembic handle schema creation, removing the explicit schema creation step.
- Updated the `migrate_canvas_data` migration to depend on the new `create_schema` migration, ensuring proper order of operations.
- Introduced a new migration file `create_schema.py` to explicitly create the database schema, improving migration reliability.
=> refactor: update database migration strategy and schema creation

src/frontend/src/ui/PadsDialog.tsx
- Updated the handleLoadPad function to accept a parameter for keeping the dialog open when switching pads.
- Modified the logic to only close the dialog if the keepDialogOpen parameter is false, improving user experience during pad deletion.
=> fix: keep pads dialog open after pad deletion

src/frontend/index.scss, src/frontend/index.tsx, src/frontend/package.json, src/frontend/src/App.tsx, src/frontend/src/AuthGate.tsx, src/frontend/src/constants.ts, src/frontend/src/css/_defaults.scss, src/frontend/src/css/_excalidraw-overrides.scss, src/frontend/src/hooks/useAppConfig.ts, src/frontend/src/lib/canvas.ts, src/frontend/src/lib/collab/Collab.tsx, src/frontend/src/ui/AuthDialog.scss, src/frontend/src/ui/AuthDialog.tsx, src/frontend/src/ui/MainMenu.tsx, src/frontend/src/ui/Range.scss, src/frontend/src/ui/SettingsDialog.tsx, src/frontend/src/ui/TabContextMenu.tsx, src/frontend/src/ui/Tabs.tsx, src/frontend/src/ui/types.ts, src/frontend/yarn.lock
This refactor is a frontend-wide clean up of unused imports, useless comments and types errors that were left over after #97
=> refactor: clean-up unused imports & fix types errors

.env.template, docker-compose.yml
As mentioned in https://github.com/pad-ws/pad.ws/issues/102
we changed the route from `/auth/callback` to `/api/auth/callback`
This PR reflect this changes in `.env.template` and `docker-compose.yml`
=> add REDIRECT_URL to .env.template

src/backend/cache/redis_client.py, src/backend/main.py
Redis client was not correctly using the same pool, this is fixed with proper singleton implementation, reducing drastically the number of open clients to Redis at any given time
=> improved redis singleton
